### ISSUE TITLE
game freezes

### ISSUE THREAD

**Issue by mali-chen** [luisp111/Stadiumcheckers#1]
clicked on red, then turn clockwise and the game is unresponsive. have to reset

**Comment by kaitlyn-atalig** [comment]
It would've been easier to see how the balls rotate to keep better track of it.

**Comment by kaitlyn-atalig** [comment]
Hard to tell which way the ring goes.

**Comment by kaitlyn-atalig** [comment]
Game is kind of hard to play when there are no instructions. It would've been better if we knew what the instructions were.
